name: Deploy to Firebase Hosting on release tag push (@confrontend/react-usa-data-charts)
'on':
  push:
    tags:
      - 'Release_@confrontend/react-usa-data-charts_v*.*.*'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACT_USA_DATA_CHARTS }}'
          channelId: live
          projectId: react-gtm
