name: Deploy to Firebase Hosting on release tag push (@confrontend/blog)
'on':
  push:
    tags:
      - 'Release_@confrontend/blog_v*.*.*'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci --legacy-peer-deps && cd packages/apps/blog && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLOG_CONFRONTEND }}'
          entryPoint: './packages/blog'
          channelId: live
          projectId: blog-confrontend
